### ISSUE TITLE
Challenge #1: Create A Range Slider

### ISSUE THREAD

**Issue by graememscott** [graememscott/company-site#3]
# Creating a range slider with Vanilla Javascript

### Step 1) Create the markup for our range slider

Lucky for us, HTML already has a built in slider element! It is actually a variation on the `<input />` element, all you need to do is add `type="range"` inside your `<input />` element like so:
```<input type="range" />```

Let's also add a class inside our `<input />` element for good measure:
```<input type="range" class="range-slider" />```

### Step 2) Select our range slider using Javascript

We can use `document.querySelector` to get the element we created in the last step that has a class of "range-slider"

```document.querySelector(".range-slider")```

### Step 3) Set up an event listener for our range slider

The two types of events that our range slider can interact with are "input" and "change". 

An event listener of type "input" will fire everytime the slider is moved.

```
document.querySelector(".range-slider").addEventListener("input", function() {
  // This will fire every time the slider changes value, in other words, everytime it is moved!
});
```

An event listener of type "change" will fire everytime the slider stops moving.

```
document.querySelector(".range-slider").addEventListener("change", function() {
  // This will fire every time the slider stops moving!
});
```

In this case, let's set it to "input" but feel free to test both out by throwing a console.log inside!

```
document.querySelector(".range-slider").addEventListener("input", function() {
  console.log('test');
});
```

### Step 4) Get the current value of our range slider

Now that we are getting our event listener to fire when we interact with our range slider, let's get the current value!

We will need to pass in the "event" argument into our event listeners function so that we can access the current range slider we are interacting with:

```
document.querySelector(".range-slider").addEventListener("input", function(event) {
  console.log(event);
});
```

Now that we can use the "event" object, we can get the current range slider by getting the "currentTarget" property from "event":

```
document.querySelector(".range-slider").addEventListener("input", function(event) {
  console.log(event.currentTarget);
});
```

Now that we have our range slider, we just need to get the "value" property!

```
document.querySelector(".range-slider").addEventListener("input", function(event) {
  console.log(event.currentTarget.value);
});
```

### Step 5) Have some fun!

Look into styling the range slider! It uses some special pseudo classes that you can learn about in the link below

https://css-tricks.com/styling-cross-browser-compatible-range-inputs-css/

Also try getting the "value" to display in the HTML!

(Hint: add another HTML element and use "innerHTML" to append the value to it!)

### Step 6) TLDR;

```
<input type="range" class="range-slider" />

<script>
  document.querySelector(".range-slider").addEventListener("input", function(event) {
    console.log(event.currentTarget.value);
  });
</script>
```

**Comment by Sam-Smyth** [comment]
All done! Pushed the changes to the master branch. This is great. It works just how I want on Chrome. On Firefox, there's a dotted border around the input range bar when you use it and when you refresh it doesn't reset to the middle. IE is messy but I don't think this stuff really works on IE. Thanks for all the detail amigo. This is exactly the type of stuff that I need.

What I would like to know how to do from here with this:

- Make multiple "break" points so it will go up or down in increments of a certain number
- Make the slider smooth but only change on these specific break points (I have an idea of how to do this with JS, so I may have a hack at it)
